// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxfwH8EWrLtE-s-WrrUIulLsVIWGiRFYM',
    appId: '1:404670781078:web:89964572c6389fdc3f94b7',
    messagingSenderId: '404670781078',
    projectId: 'airsense5g',
    authDomain: 'airsense5g.firebaseapp.com',
    storageBucket: 'airsense5g.firebasestorage.app',
    measurementId: 'G-9HD490RMCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuzLj8EwLvaDJ2mZp2HMOQZP5q1ga0TcA',
    appId: '1:404670781078:android:4b965f120b561f173f94b7',
    messagingSenderId: '404670781078',
    projectId: 'airsense5g',
    storageBucket: 'airsense5g.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQgNPgXW5F44gIs5Vc6rNyWFi8wIKuEI0',
    appId: '1:404670781078:ios:0bd8c1b888ec01fc3f94b7',
    messagingSenderId: '404670781078',
    projectId: 'airsense5g',
    storageBucket: 'airsense5g.firebasestorage.app',
    iosClientId: '404670781078-3un746m9i6csg39johf2o1e7gluf8523.apps.googleusercontent.com',
    iosBundleId: 'com.example.airsense5g',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQgNPgXW5F44gIs5Vc6rNyWFi8wIKuEI0',
    appId: '1:404670781078:ios:0bd8c1b888ec01fc3f94b7',
    messagingSenderId: '404670781078',
    projectId: 'airsense5g',
    storageBucket: 'airsense5g.firebasestorage.app',
    iosClientId: '404670781078-3un746m9i6csg39johf2o1e7gluf8523.apps.googleusercontent.com',
    iosBundleId: 'com.example.airsense5g',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxfwH8EWrLtE-s-WrrUIulLsVIWGiRFYM',
    appId: '1:404670781078:web:66b148dcb3c46a383f94b7',
    messagingSenderId: '404670781078',
    projectId: 'airsense5g',
    authDomain: 'airsense5g.firebaseapp.com',
    storageBucket: 'airsense5g.firebasestorage.app',
    measurementId: 'G-P5F5CG2N2B',
  );

}